### ISSUE TITLE
Pay for an order

### ISSUE THREAD

**Issue by copypastedeveloper** [nss-bladeRunners/Orientation-Api#11]
As a Accounts Receivable rep, I want to mark an order as 'Paid',  So that I will know which orders have outstanding payments.

**Comment by waamber** [comment]
```
Add payment date to order
Query to update order to set the date 

setPaymentDate = getOrderDate
update where OrderId =addOrderId
```

**Comment by gib-bowden** [comment]
Order cannot be "open"; Payment Date cannot be applied twice
